### PR TITLE
[WIP]Modernize 1

### PR DESCRIPTION
**Pull request by mimol91**

### CODE REVIEW

**Comment by malef** [comment]
@mimol91 Is this still work in progress? Or is it abandoned?

**Comment by mimol91** [comment]
@malef 
I need to test it.
Could you provide some example of docker-compose file with {{{ }}} variables? I am not sure how to use it and what variables are available

**Comment by malef** [comment]
Hello @mimol91 and sorry for a late answer.

There is no interpolation for `docker-compose.yml` file.

What will be interpolated are some values in build definition configuration, example of which is given below:
```json
{
  "projectId": "58a41db04ace19391d7f7e3c",
  "name": "Example build",
  "components": [
    {
      "id": "templates",
      "sourceName": "xsolve-pl/docker-templates",
      "referenceType": "branch",
      "referenceName": "feat-reduced",
      "beforeBuildTasks": [
        {
          "type": "copy",
          "sourceRelativePath": "PHP/app/config/parameters.yml.feat.dist",
          "destinationRelativePath": "PHP/app/config/parameters.yml"
        },
        {
          "type": "interpolate",
          "relativePath": "PHP/app/config/parameters.yml"
        },
        {
          "type": "copy",
          "sourceRelativePath": "PHP/web/app_dev.php.dist",
          "destinationRelativePath": "PHP/web/app_dev.php"
        }
      ]
    }
  ],
  "externalPorts": [
    {
      "id": "php",
      "rangeStart": 8000,
      "rangeEnd": 8099
    },
    {
      "id": "mailcatcher",
      "rangeStart": 8000,
      "rangeEnd": 8099
    }
  ],
  "environmentalVariables": [
    {
      "name": "PHP_EXTERNAL_URL",
      "value": "{{{scheme}}}://{{{domain}}}:{{{port.php}}}"
    }
  ],
  "composeFile": {
    "componentId": "templates",
    "relativePath": "Suite/docker-compose.yml"
  },
  "summaryItems": [
    {
      "name": "Symfony app URL",
      "value": "{{{scheme}}}://{{{domain}}}:{{{port.php}}}"
    },
    {
      "name": "Mailcatcher URL",
      "value": "{{{scheme}}}://{{{domain}}}:{{{port.mailcatcher}}}"
    }
  ]
}
```

Also some parameter files can be interpolated for each component, but I can't share any example at the moment. Let me know if you need one as well.

**Comment by adam-szaraniec** [comment]
I ll try to test it soon, (currently my internet speed is very limited)

**Pull request closed without merging**
